### ISSUE TITLE
Adding the locale to the edit button

### ISSUE THREAD

**Issue by echantigny** [wbrowar/adminbar#10]
Hi, 

I think its self explanatory.  When clicking the edit link, it should link to the current locale.

Thanks,
Eric

**Comment by wbrowar** [comment]
Hey @echantigny, I _think_ the current locale should work for the edit link. Are you getting an error, or is it only working for the default locale?

**Comment by echantigny** [comment]
Hi @wbrowar ,

It seems to always open in the language your CP is set in, instead of the language of the page you are visiting.  My CP is in english, if I visit a French page and click edit, I get the english edit page. 

Easy fix is to alway add the locale at the end of the CP link
ie: /entries/pages/829-new-features/fr_ca

Eric

**Comment by wbrowar** [comment]
Hi @echantigny, I'm really sorry this took so long to take care of, but I finally got a chance to push an update that hopefully fixes this issue. Please download the latest and let me know if this works as intended.

-Will

**Comment by adamsmt** [comment]
Hello @wbrowar, I'm noticing that this update may have caused an error to the en_us. Clicking any of the "edit page" buttons while on the front end seems to add en_us to the URL and will throw a 404.

**Comment by wbrowar** [comment]
Hey @adamsmt I added the entry's locale to the end of the URL, but from my testing it should switch the locale based on the entry element that's passed in. Is it happening on all pages, or just in certain situations?

**Comment by adamsmt** [comment]
Hey @wbrowar, in my build it's happening on each page of the site. I'm running a local copy which is not upgraded to the professional version, and I think locales are a feature of the upgraded version of Craft. I think the issue lies in the default locale. It looks like the default locale does not require the addition of the /en_us information added to the end of the edit link, or it could be that if there's only 1 locale available, it ignores this additional url feature. I was able to correct this locally on my end by adding this `{%if entry.locale == "en_us" %}{{ url(entry.cpEditUrl ~ '/') }}{% else %}{{ url(entry.cpEditUrl ~ '/' ~ entry.locale) }}{% endif %}` to the bar.html file at line 28. I'm not sure if there's a way to make this more specific to the default locale or not.

**Comment by wbrowar** [comment]
Ah, I didn't realize that this was what happened on non Pro sites. I've just fixed it and I'll push out an update in a little bit. Thanks for letting me know about this bug :)
